import React from 'react'
import Head from 'next/head'
import style from '@/styles/FroggieLayout.module.sass'
import FroggieNavbar from './FroggieNavbar'
import FroggieFooter from './FroggieFooter'
export default function FroggieLayout({children}) {
    return(
        <div className={style.allPage}>
            <Head>
                <title>Froggie Slottery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/frgst_logo.svg" />
            </Head>
            <FroggieNavbar />
            <main className={style.main}>
                {children}
            </main>
            <FroggieFooter />
        </div>
    )
}