import React from 'react'
import RespNavbar from './RespNavbar'
import Footer from './Footer'
import styles from '../styles/Layout.module.sass'
import Head from 'next/head'

export default function Layout({children}) {
  return (
    <div className={styles.all}>
        <Head>
            <title>Lottery</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/#" />
        </Head>
        <RespNavbar />
        <main className={styles.main}>{children}</main>
        <Footer />
    </div>
  )
}
